---
title: "generative_models"
author: "Sadia Boksh"
date: "13/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dslabs)
library(caret)
library(tidyverse)
data("tissue_gene_expression")
      
# set.seed(1993) #if using R 3.5 or earlier
set.seed(1993, sample.kind="Rounding") # if using R 3.6 or later
ind <- which(tissue_gene_expression$y %in% c("cerebellum", "hippocampus"))
y <- droplevels(tissue_gene_expression$y[ind])
x <- tissue_gene_expression$x[ind, ]
x <- x[, sample(ncol(x), 10)]

train_lda <- train(x, y, method = "lda", preProcess="center")

train_lda$results

df <- as.data.frame(t(train_lda$finalModel$means))

df %>% ggplot(aes(cerebellum, hippocampus, label=rownames(.))) + geom_point()+geom_text()+geom_abline()

          
fit_lda <- train(x, y, method = "lda", preProcess = "center")
fit_lda$results["Accuracy"]
t(fit_lda$finalModel$means) %>% data.frame() %>%
	mutate(predictor_name = rownames(.)) %>%
	ggplot(aes(predictor_name, hippocampus)) +
	geom_point() +
	coord_flip()
# 
#   d <- apply(train_lda$finalModel$means, 2, diff)
# ind <- order(abs(d), decreasing = TRUE)[1:2]
# plot(x[, ind], col = y)



#using all output classes
# set.seed(1993) # if using R 3.5 or earlier
set.seed(1993, sample.kind="Rounding") # if using R 3.6 or later
y <- tissue_gene_expression$y
x <- tissue_gene_expression$x
x <- x[, sample(ncol(x), 10)]

train_lda <- train(x, y, method = "lda", preProcess="center")

train_lda$results

df <- as.data.frame(t(train_lda$finalModel$means))




```



```{r}

library(dslabs)      
library(caret)
data("tissue_gene_expression")
      
set.seed(1993) #set.seed(1993, sample.kind="Rounding") if using R 3.6 or later
ind <- which(tissue_gene_expression$y %in% c("cerebellum", "hippocampus"))
y <- droplevels(tissue_gene_expression$y[ind])
x <- tissue_gene_expression$x[ind, ]
x <- x[, sample(ncol(x), 10)]

train_qda <- train(x, y, method = "qda")

train_qda$results

df <- as.data.frame(t(train_qda$finalModel$means))

df %>% ggplot(aes(cerebellum, hippocampus, label=rownames(.))) + geom_point()+geom_text(nudge_x = 0.4, check_overlap = TRUE)

```
