---
title: "linear_model"
author: "Sadia Boksh"
date: "26/11/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Lahman)
library(rmarkdown)
library(tidyverse)
library(dplyr)
```

# Baseball
## Scatter plot of the relationship between at bat and runs per game
```{r}
data("Teams")

Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(AB_per_game = AB/G, R_per_game = R/G) %>%
    ggplot(aes(AB_per_game, R_per_game)) + 
    geom_point(alpha = 0.5) 


Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(AB_per_game = AB/G, R_per_game = R/G) %>%
  summarize(r = cor(AB_per_game, R_per_game))
```

##Scatterplot of the relationsip between wins per game vs number of fielding errors per game
```{r}
Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(wins_per_game = W/G, E_per_game = E/G) %>%
    ggplot(aes(E_per_game, wins_per_game)) + 
    geom_point(alpha = 0.5)

Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(wins_per_game = W/G, E_per_game = E/G) %>%
  summarize(r = cor(wins_per_game, E_per_game))

```
##Scatterplot of the relationsip between triples (X3B) per game versus doubles (X2B) per game.
```{r}
Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(X3B_per_game = X3B/G, X2B_per_game = X2B/G) %>%
    ggplot(aes(X2B_per_game, X3B_per_game)) + 
    geom_point(alpha = 0.5)

Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(X3B_per_game = X3B/G, X2B_per_game = X2B/G) %>%
  summarize(r = cor(X3B_per_game, X2B_per_game))
```

```{r}
library(Lahman)
bat_02 <- Batting %>% filter(yearID == 2002) %>%
    mutate(pa = AB + BB, singles = (H - X2B - X3B - HR)/pa, bb = BB/pa) %>%
    filter(pa >= 100) %>%
    select(playerID, singles, bb)

bat_99_01 <- Batting %>% filter(yearID %in% c(1999:2001)) %>%
    mutate(pa = AB + BB, singles = (H - X2B - X3B - HR)/pa, bb = BB/pa) %>%
    filter(pa >= 100) %>%
    select(playerID, singles, bb)

avg_singles<- bat_99_01 %>% group_by(playerID) %>%
              summarize(mean_singles = mean(singles), mean_bb = mean(bb))

avg_singles %>% count(mean_singles > 0.2)
            
avg_bb <- bat_99_01 %>% group_by(playerID) %>%
              summarize(mean_singles = mean(singles), mean_bb = mean(bb))


avg_bb %>%count(mean_bb > 0.2)
singles <- inner_join(bat_02, avg_singles, by="playerID")
singles %>%  summarise(cor_singles = cor(singles, mean_singles) )
bbs <- inner_join(bat_02, avg_bb, by="playerID") 
bbs%>% summarise(cor_bb = cor(bb, mean_bb) )


singles %>% ggplot(aes(singles, mean_singles)) + 
  geom_point()
bbs %>% ggplot(aes(bb, mean_bb)) + 
  geom_point()

fit_singles_02<- lm(singles ~ mean_singles, data=singles)
summary(fit_singles_02)

fit_bb_02<- lm(bb ~ mean_bb, data=bbs)
summary(fit_bb_02)

```
```{r}
pa_per_game <- Batting %>% 
  filter(yearID == 2002) %>% 
  group_by(teamID) %>%
  summarize(pa_per_game = sum(AB+BB)/max(G)) %>% 
  .$pa_per_game %>% 
  mean

BB <-2
singles <- 4
doubles <- 1
triples <- 0
HR <- 1

teamA <- -2.769 + 0.371 *  BB + 0.519* singles + 0.771 *doubles + 1.24*triples + 1.443*HR

BB <-1
singles <- 6
doubles <- 2
triples <- 1
HR <- 0

teamB <- -2.769 + 0.371 *  BB + 0.519* singles + 0.771 *doubles + 1.24*triples + 1.443*HR
```
```{r}
data("Teams")
Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(R_per_game = R/G, bb_per_game = BB/G, HR_per_game=HR/G) %>%
    lm(R_per_game ~ bb_per_game+HR_per_game, data=.) %>%
    .$coef
```
```{r}
Teams %>% filter(yearID == 1971) %>% 
          do(tidy(lm(R ~ BB+HR , data=.))) %>% filter(p.value < 0.05)
```
```{r}
Teams %>% filter(yearID %in% c(1961:2018)) %>% 
          group_by(yearID)%>%
          do(tidy(lm(R ~ BB+HR , data=.), conf.int=TRUE)) %>% 
          filter(term == "BB") %>%
          ggplot(aes(yearID, y=estimate)) +
          geom_point()+
          geom_smooth(method = "lm")
       
  
```
```{r}

bb_fit<- Teams %>% filter(yearID %in% c(1961:2018)) %>% 
          group_by(yearID)%>%
          do(tidy(lm(R ~ BB+HR , data=.), conf.int=TRUE)) %>% 
          filter(term == "BB")

fit <- bb_fit %>% lm(estimate ~ yearID, data=.)
summary(fit)
```

# Galton Families
```{r}


set.seed(1989) #if you are using R 3.5 or earlier
set.seed(1989, sample.kind="Rounding") #if you are using R 3.6 or later
library(HistData)
data("GaltonFamilies")

female_heights <- GaltonFamilies%>%     
    filter(gender == "female") %>%     
    group_by(family) %>%     
    sample_n(1) %>%     
    ungroup() %>%     
    select(mother, childHeight) %>%     
    rename(daughter = childHeight)


mu_m_h <- mean(female_heights$mother)
sd_m_h <- sd(female_heights$mother)
mu_d_h <- mean(female_heights$daughter)
sd_d_h <- sd(female_heights$daughter)
r_md <-  mean(scale(female_heights$mother)* scale(female_heights$daughter))
m <- r_md*sd_d_h/sd_m_h
b <- mu_d_h - m*mu_m_h
perc_var = r_md^2*100
y <- m*60+b 
```

```{r}
set.seed(1989) #if you are using R 3.5 or earlier
set.seed(1989, sample.kind="Rounding") #if you are using R 3.6 or later
library(HistData)
data("GaltonFamilies")
options(digits = 3)    # report 3 significant digits

female_heights <- GaltonFamilies %>%     
    filter(gender == "female") %>%     
    group_by(family) %>%     
    sample_n(1) %>%     
    ungroup() %>%     
    select(mother, childHeight) %>%     
    rename(daughter = childHeight)

fit <- female_heights %>% lm(mother ~ daughter, data=.)
summary(fit)
y_hat <- predict(fit)
resid <- female_heights$mother - y_hat
female_heights$mother %>% head(1)
```


```{r}
library(tidyverse)
library(HistData)
data("GaltonFamilies")

set.seed(1983)
galton_heights <- GaltonFamilies %>%
  filter(gender == "male") %>%
  group_by(family) %>%
  sample_n(1) %>%
  ungroup() %>%
  select(father, childHeight) %>%
  rename(son = childHeight)
rss <- function(beta0, beta1, data){
  resid <- galton_heights$son - (beta0+beta1*galton_heights$father)
  return(sum(resid^2))
}

beta1 = seq(0, 1, len=nrow(galton_heights))
results <- data.frame(beta1 = beta1,
                      rss = sapply(beta1, rss, beta0 = 36))
results %>% ggplot(aes(beta1, rss)) + geom_line() + 
  geom_line(aes(beta1, rss), col=2)
```
# COnfidence intervals
```{r}

galton_heights %>% ggplot(aes(father, son)) +
    geom_point() +
    geom_smooth(method = "lm")
 
model <- lm(son ~ father, data = galton_heights)
predictions <- predict(model, interval = c("confidence"), level = 0.95)
data <- as_tibble(predictions) %>% bind_cols(father = galton_heights$father)

ggplot(data, aes(x = father, y = fit)) +
    geom_line(color = "blue", size = 1) + 
    geom_ribbon(aes(ymin=lwr, ymax=upr), alpha=0.2) + 
    geom_point(data = galton_heights, aes(x = father, y = son))
        
```
```{r}
library(tidyverse)
library(HistData)
data("GaltonFamilies")
set.seed(1) # if you are using R 3.5 or earlier
set.seed(1, sample.kind = "Rounding") # if you are using R 3.6 or later
galton <- GaltonFamilies %>%
    group_by(family, gender) %>%
    sample_n(1) %>%
    ungroup() %>% 
    gather(parent, parentHeight, father:mother) %>%
    mutate(child = ifelse(gender == "female", "daughter", "son")) %>%
    unite(pair, c("parent", "child"))

galton
```
## Summarize the number of observations in each group
```{r}
galton %>% group_by(pair) %>% summarize(n=n(), cor_coeff=cor(childHeight, parentHeight))
```
## Estimates
```{r}
galton %>% group_by(pair) %>%
          do(tidy(lm(childHeight ~ parentHeight, data=.), conf.int=TRUE)) %>%
   filter(term == "parentHeight") %>%
          select(pair, estimate, conf.low, conf.high) %>%
 
  ggplot(aes(pair, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_errorbar() +
  geom_point()
```


